name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  - type: dropdown
    id: contract
    attributes:
      label: Which contract is affected?
      multiple: true
      options:
        - bitsave.clar (main contract)
        - bitsave-badges.clar (NFT system)
        - bitsave-referrals.clar (referral system)
        - bitsave-upgrade.clar (upgrade management)
        - Frontend application
        - Not sure
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (funds at risk, system down)
        - High (major functionality broken)
        - Medium (some functionality affected)
        - Low (minor issue, workaround available)
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      value: |
        - OS: [e.g. macOS, Ubuntu, Windows]
        - Node version: [e.g. 18.0.0]
        - Clarinet version: [e.g. 1.5.0]
        - Network: [mainnet/testnet/devnet]
        - Browser: [if frontend issue]
      render: markdown
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
