name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
  
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternatively, we could...
  
  - type: dropdown
    id: component
    attributes:
      label: Which component would this affect?
      multiple: true
      options:
        - Smart contracts
        - Frontend interface
        - API/Backend
        - Documentation
        - Testing
        - DevOps/Infrastructure
        - Not sure
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (would significantly improve experience)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case or scenario where this feature would be helpful.
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].
        
        Example scenario:
        1. User does X
        2. System should do Y
        3. User benefits by Z
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be implemented for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
  
  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (if known)
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (few hours)
        - Medium (few days)
        - Complex (few weeks)
        - Very Complex (months)
        - Not sure
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
  
  - type: checkboxes
    id: research
    attributes:
      label: Research
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested before
          required: true
        - label: I have read the project documentation
          required: true
        - label: I understand this is a feature request and not a bug report
          required: true
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
