;; Analytics tracking
(define-map daily-active-users uint uint)
(define-map monthly-active-users uint uint)
(define-map total-value-locked uint uint)
(define-map daily-deposits uint uint)
(define-map daily-withdrawals uint uint)
(define-map user-retention-rate uint uint)
(define-map average-deposit-size uint uint)
(define-map average-lock-period uint uint)
(define-map badges-minted-daily uint uint)
(define-map referral-conversions uint uint)
(define-map protocol-revenue uint uint)
