;; Insurance pool
(define-data-var insurance-pool-balance uint u0)
(define-map insured-deposits principal uint)
(define-data-var insurance-premium uint u1)
;; Vault insurance mechanism
;; Vault insurance mechanism
<!-- update 1 -->
<!-- update 2 -->
<!-- update 3 -->
<!-- update 4 -->
<!-- update 5 -->
<!-- update 6 -->
<!-- update 7 -->
<!-- update 8 -->
<!-- update 9 -->
<!-- update 10 -->
<!-- update 11 -->
<!-- update 12 -->
<!-- update 13 -->
<!-- update 14 -->
<!-- update 15 -->
