;; Staking contract
;; Advanced staking features
(define-data-var staking-enabled bool true)
(define-map staking-pools uint {name: (string-ascii 50), apy: uint})
(define-map user-staking-pool principal uint)
(define-data-var flexible-staking-apy uint u5)
(define-data-var locked-30-apy uint u8)
(define-data-var locked-90-apy uint u12)
(define-data-var locked-180-apy uint u18)
(define-data-var locked-365-apy uint u25)
(define-map user-staking-tier principal uint)
(define-map tier-multipliers uint uint)
(define-map auto-restake-preference principal bool)
(define-data-var restake-bonus uint u5)
(define-map staking-rewards-claimed principal uint)
(define-map pending-rewards principal uint)
(define-data-var total-staking-rewards uint u0)
(define-map compound-frequency principal uint)
(define-data-var min-compound-amount uint u1000000)
(define-map last-compound-time principal uint)
(define-map staking-start-block principal uint)
;; Staking rewards pool
;; Staking rewards pool
<!-- update 1 -->
<!-- update 2 -->
<!-- update 3 -->
<!-- update 4 -->
<!-- update 5 -->
<!-- update 6 -->
<!-- update 7 -->
<!-- update 8 -->
<!-- update 9 -->
<!-- update 10 -->
<!-- update 11 -->
<!-- update 12 -->
<!-- update 13 -->
<!-- update 14 -->
<!-- update 15 -->
<!-- update 16 -->
<!-- update 17 -->
<!-- update 18 -->
<!-- update 19 -->
<!-- update 20 -->
<!-- update 21 -->
<!-- update 22 -->
<!-- update 23 -->
<!-- update 24 -->
<!-- update 25 -->
