#!/bin/bash
cd /home/marcus/Bitsave-Stacks
c=120
mc() { echo "$2" >> "$1"; git add .; git commit -m "$3" -q; ((c++)); echo "[$c/200] $3"; }

# 121-160: Frontend components
mc "frontend/src/components/BadgeDisplay.tsx" "// Badge display component" "feat(frontend): add BadgeDisplay component"
mc "frontend/src/components/BadgeGallery.tsx" "// Badge gallery component" "feat(frontend): add BadgeGallery component"
mc "frontend/src/components/ReputationDashboard.tsx" "// Reputation dashboard" "feat(frontend): add ReputationDashboard"
mc "frontend/src/components/SavingsCalculator.tsx" "// Savings calculator" "feat(frontend): add SavingsCalculator"
mc "frontend/src/components/DepositForm.tsx" "// Enhanced deposit form" "feat(frontend): add DepositForm component"
mc "frontend/src/components/WithdrawalInterface.tsx" "// Withdrawal interface" "feat(frontend): add WithdrawalInterface"
mc "frontend/src/components/TransactionHistory.tsx" "// Transaction history" "feat(frontend): add TransactionHistory"
mc "frontend/src/components/NotificationSystem.tsx" "// Notification system" "feat(frontend): add NotificationSystem"
mc "frontend/src/components/UserProfile.tsx" "// User profile page" "feat(frontend): add UserProfile component"
mc "frontend/src/components/Leaderboard.tsx" "// Leaderboard component" "feat(frontend): add Leaderboard component"
mc "frontend/src/components/AnalyticsDashboard.tsx" "// Analytics dashboard" "feat(frontend): add AnalyticsDashboard"
mc "frontend/src/components/MobileNav.tsx" "// Mobile navigation" "feat(frontend): add mobile navigation"
mc "frontend/src/components/ResponsiveLayout.tsx" "// Responsive layout" "feat(frontend): add responsive layout"
mc "frontend/src/hooks/useBadges.ts" "// Badge hooks" "feat(frontend): add useBadges hook"
mc "frontend/src/hooks/useReputation.ts" "// Reputation hooks" "feat(frontend): add useReputation hook"
mc "frontend/src/hooks/useDeposit.ts" "// Deposit hooks" "feat(frontend): add useDeposit hook"
mc "frontend/src/hooks/useWithdrawal.ts" "// Withdrawal hooks" "feat(frontend): add useWithdrawal hook"
mc "frontend/src/hooks/useNotifications.ts" "// Notification hooks" "feat(frontend): add useNotifications hook"
mc "frontend/src/services/badgeService.ts" "// Badge service" "feat(frontend): add badge service"
mc "frontend/src/services/contractService.ts" "// Contract service" "feat(frontend): add contract service"
mc "frontend/src/services/analyticsService.ts" "// Analytics service" "feat(frontend): add analytics service"
mc "frontend/src/utils/formatters.ts" "// Utility formatters" "feat(frontend): add formatter utilities"
mc "frontend/src/utils/validators.ts" "// Input validators" "feat(frontend): add validator utilities"
mc "frontend/src/utils/calculations.ts" "// Calculation helpers" "feat(frontend): add calculation utilities"
mc "frontend/src/styles/badges.css" "/* Badge styles */" "style(frontend): add badge styles"
mc "frontend/src/styles/dashboard.css" "/* Dashboard styles */" "style(frontend): add dashboard styles"
mc "frontend/src/styles/mobile.css" "/* Mobile styles */" "style(frontend): add mobile styles"
mc "frontend/src/styles/animations.css" "/* Animations */" "style(frontend): add animations"
mc "frontend/src/config/contracts.ts" "// Contract addresses" "config(frontend): add contract config"
mc "frontend/src/config/networks.ts" "// Network config" "config(frontend): add network config"
mc "scripts/deploy-frontend.sh" "#!/bin/bash" "chore(scripts): add frontend deployment script"
mc "scripts/build-frontend.sh" "#!/bin/bash" "chore(scripts): add frontend build script"
mc "scripts/test-frontend.sh" "#!/bin/bash" "chore(scripts): add frontend test script"
mc ".github/workflows/frontend-ci.yml" "name: Frontend CI" "ci: add frontend CI workflow"
mc ".github/workflows/contract-ci.yml" "name: Contract CI" "ci: add contract CI workflow"
mc ".github/workflows/deploy-production.yml" "name: Deploy Production" "ci: add production deployment workflow"
mc "docker/frontend.Dockerfile" "FROM node:18" "chore(docker): add frontend Dockerfile"
mc "docker/backend.Dockerfile" "FROM node:18" "chore(docker): add backend Dockerfile"
mc "docker/nginx.conf" "server {}" "chore(docker): add nginx config"
mc "docker-compose.prod.yml" "version: '3.8'" "chore(docker): add production compose file"

echo "Completed 160 commits!"
