export const ERROR_CODES = {
  ERR_NO_AMOUNT: 100,
  ERR_ALREADY_DEPOSITED: 101,
  ERR_ALREADY_WITHDRAWN: 102,
  ERR_LOCK_ACTIVE: 103,
  ERR_NO_DEPOSIT: 104,
  ERR_NOT_AUTHORIZED: 105,
  ERR_CONTRACT_PAUSED: 106,
  ERR_BELOW_MINIMUM: 107,
  ERR_EXCEEDS_MAXIMUM: 108,
  ERR_WITHDRAWAL_COOLDOWN: 109,
  ERR_INVALID_LOCK_PERIOD: 110,
  ERR_REENTRANCY_GUARD: 111,
  ERR_OVERFLOW_PROTECTION: 112,
  ERR_INVALID_PRINCIPAL: 113,
  ERR_RATE_LIMIT_EXCEEDED: 114
};
